### ISSUE TITLE
Allow access of classes without the `import` keyword

### ISSUE THREAD

**Issue by CaptainBaldi** [TahirKarabekiroglu/SScript#1]
In Haxe, you can access a class by doing

```
import backend.Utility;

trace(Utility.someFunction());
```

Or alternatively,

`trace(backend.Utility.someFunction());`

However, SScript can only do the former. 

Being able to access a class without importing it can be convenient. For example, you might only want to use a specific class once without importing it.

**Comment by TahirKarabekiroglu** [comment]
This has been tried, unfortunately it is not possible to implement this without breaking normal access.

**Comment by CaptainBaldi** [comment]
Alright, good to know.
